USE HowKteam
GO

--SELECT * FROM dbo.GIAOVIEN

--SELECT * FROM dbo.NGUOITHAN

-- code chuẩn
SELECT MAGV FROM dbo.GIAOVIEN
WHERE LUONG > 25000
UNION
SELECT MAGV FROM dbo.NGUOITHAN
WHERE PHAI = N'Nữ'

-- Nếu muốn lấy tất cả các record duplicate thì thêm ALL
SELECT MAGV FROM dbo.GIAOVIEN
WHERE LUONG > 25000
UNION ALL
SELECT MAGV FROM dbo.NGUOITHAN
WHERE PHAI = N'Nữ'